Repository AdobeDocs/commerce-cloud-tools, pull requests merged in 2022-12, with the labels that each got.

#22 COMDOX-85 Cloud docker migration
  .gitignore
  README.md
  src/data/navigation/header.js
  src/data/navigation/sections/docker.js
  src/data/navigation/sections/index.js
  src/pages/_images/banner-hex-violet.png
  src/pages/_images/xdebug/edit.png
  src/pages/_images/xdebug/enable.png
  src/pages/_images/xdebug/helper-icon.png
  src/pages/_images/xdebug/helper-options.png
  src/pages/_images/xdebug/listening.png
  src/pages/docker/configure/configuration-sources.md
  src/pages/docker/configure/custom-docker-compose.md
  src/pages/docker/configure/extend-docker-configuration.md
  src/pages/docker/configure/index.md
  src/pages/docker/configure/manage-cron-jobs.md
  src/pages/docker/configure/manage-database.md
  src/pages/docker/configure/multiple-sites.md
  src/pages/docker/containers/cli.md
  src/pages/docker/containers/index.md
  src/pages/docker/containers/service.md
  src/pages/docker/deploy/developer-mode.md
  src/pages/docker/deploy/index.md
  src/pages/docker/deploy/production-mode.md
  src/pages/docker/get-support.md
  src/pages/docker/index.md
  src/pages/docker/quick-reference.md
  src/pages/docker/setup/index.md
  src/pages/docker/setup/initialize-docker.md
  src/pages/docker/setup/synchronize-data.md
  src/pages/docker/test.md
  src/pages/docker/test/application-testing.md
  src/pages/docker/test/blackfire.md
  src/pages/docker/test/code-testing.md
  src/pages/docker/test/configure-xdebug.md
  src/pages/docker/test/index.md
  src/pages/docker/upgrade-docker-package.md
  src/pages/index.md
Labels: migration

#23 COMDOX-372 Add project board workflow
  .github/workflows/add-to-project-board.yml
Labels: maintenance

#25 Add issue templates from upstream template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/incorrect_topic.yaml
  .github/ISSUE_TEMPLATE/missing_content.yaml
  .github/ISSUE_TEMPLATE/site_bug.yaml
  .github/ISSUE_TEMPLATE/site_feature.yaml
Labels: maintenance

#26 Update navigation header to include link to Commerce devdocs index page
  gatsby-config.js
  src/data/navigation/header.js
Labels: enhancement
