Repository AdobeDocs/commerce-cloud-tools, pull requests merged in 2023-11, with the labels that each got.

#73 COMDOX-830: Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#74 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#76 Fix broken URLs
  src/pages/docker/containers/service.md
  src/pages/docker/test/blackfire.md
Labels: editorial

#75 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: enhancement

#77 Add validation for custom headers
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: bug, enhancement

#78 Update theme and caniuse-lite
  yarn.lock
Labels: dependencies
