Repository AdobeDocs/commerce-cloud-tools, pull requests merged in 2023-03, with the labels that each got.

#36 Prepare for required workflow
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  package.json
  yarn.lock
Labels: maintenance

#39 Change indexing cron to monthly
  .github/workflows/index.yml
Labels: maintenance

#37 MCLOUD-10080: Release Cloud Tools
  src/pages/docker/containers/index.md
  src/pages/docker/containers/service.md
Labels: major update, internal

#41 Update service versions, MCD and Magento version
  src/pages/docker/configure/configuration-sources.md
  src/pages/docker/setup/initialize-docker.md
Labels: technical, internal

#40 Support for Commerce 2.4.6
  src/pages/docker/configure/configuration-sources.md
  src/pages/docker/index.md
  src/pages/docker/setup/initialize-docker.md
  src/pages/docker/test/configure-xdebug.md
Labels: major update

#43 COMDOX-588: Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#44 Update MFTF configuration
  src/pages/docker/test/application-testing.md
Labels: technical, internal

#45 Update README.md
  README.md
Labels: maintenance

#46 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: maintenance, dependencies
