Repository AdobeDocs/commerce-cloud-tools, pull requests merged in 2023-01, with the labels that each got.

#27 add link to release and unify the PR template
  .github/PULL_REQUEST_TEMPLATE.md
  src/pages/index.md
Labels: editorial

#28 COMDOX-328: Port 2.4.6-develop changes from magento-commerce/devdocs
  src/pages/docker/configure/configuration-sources.md
  src/pages/docker/setup/initialize-docker.md
Labels: technical

#29 Clean up the Docker formatting and grammar
  src/pages/docker/configure/custom-docker-compose.md
  src/pages/docker/configure/extend-docker-configuration.md
  src/pages/docker/configure/index.md
  src/pages/docker/configure/manage-cron-jobs.md
  src/pages/docker/configure/manage-database.md
  src/pages/docker/configure/multiple-sites.md
  src/pages/docker/containers/cli.md
  src/pages/docker/containers/index.md
  src/pages/docker/containers/service.md
  src/pages/docker/deploy/developer-mode.md
  src/pages/docker/deploy/index.md
  src/pages/docker/deploy/production-mode.md
  src/pages/docker/get-support.md
  src/pages/docker/quick-reference.md
  src/pages/docker/setup/index.md
  src/pages/docker/setup/initialize-docker.md
  src/pages/docker/setup/synchronize-data.md
  src/pages/docker/test/application-testing.md
  src/pages/docker/test/blackfire.md
  src/pages/docker/test/code-testing.md
  src/pages/docker/upgrade-docker-package.md
Labels: major update
